// Code generated by ent, DO NOT EDIT.

package model_ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ice-bergtech/dnh/src/internal/model_ent/asninfo"
	"github.com/ice-bergtech/dnh/src/internal/model_ent/predicate"
)

// ASNInfoQuery is the builder for querying ASNInfo entities.
type ASNInfoQuery struct {
	config
	ctx        *QueryContext
	order      []asninfo.OrderOption
	inters     []Interceptor
	predicates []predicate.ASNInfo
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ASNInfoQuery builder.
func (aiq *ASNInfoQuery) Where(ps ...predicate.ASNInfo) *ASNInfoQuery {
	aiq.predicates = append(aiq.predicates, ps...)
	return aiq
}

// Limit the number of records to be returned by this query.
func (aiq *ASNInfoQuery) Limit(limit int) *ASNInfoQuery {
	aiq.ctx.Limit = &limit
	return aiq
}

// Offset to start from.
func (aiq *ASNInfoQuery) Offset(offset int) *ASNInfoQuery {
	aiq.ctx.Offset = &offset
	return aiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aiq *ASNInfoQuery) Unique(unique bool) *ASNInfoQuery {
	aiq.ctx.Unique = &unique
	return aiq
}

// Order specifies how the records should be ordered.
func (aiq *ASNInfoQuery) Order(o ...asninfo.OrderOption) *ASNInfoQuery {
	aiq.order = append(aiq.order, o...)
	return aiq
}

// First returns the first ASNInfo entity from the query.
// Returns a *NotFoundError when no ASNInfo was found.
func (aiq *ASNInfoQuery) First(ctx context.Context) (*ASNInfo, error) {
	nodes, err := aiq.Limit(1).All(setContextOp(ctx, aiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{asninfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aiq *ASNInfoQuery) FirstX(ctx context.Context) *ASNInfo {
	node, err := aiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ASNInfo ID from the query.
// Returns a *NotFoundError when no ASNInfo ID was found.
func (aiq *ASNInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aiq.Limit(1).IDs(setContextOp(ctx, aiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{asninfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aiq *ASNInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := aiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ASNInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ASNInfo entity is found.
// Returns a *NotFoundError when no ASNInfo entities are found.
func (aiq *ASNInfoQuery) Only(ctx context.Context) (*ASNInfo, error) {
	nodes, err := aiq.Limit(2).All(setContextOp(ctx, aiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{asninfo.Label}
	default:
		return nil, &NotSingularError{asninfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aiq *ASNInfoQuery) OnlyX(ctx context.Context) *ASNInfo {
	node, err := aiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ASNInfo ID in the query.
// Returns a *NotSingularError when more than one ASNInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (aiq *ASNInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aiq.Limit(2).IDs(setContextOp(ctx, aiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{asninfo.Label}
	default:
		err = &NotSingularError{asninfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aiq *ASNInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := aiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ASNInfos.
func (aiq *ASNInfoQuery) All(ctx context.Context) ([]*ASNInfo, error) {
	ctx = setContextOp(ctx, aiq.ctx, ent.OpQueryAll)
	if err := aiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ASNInfo, *ASNInfoQuery]()
	return withInterceptors[[]*ASNInfo](ctx, aiq, qr, aiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aiq *ASNInfoQuery) AllX(ctx context.Context) []*ASNInfo {
	nodes, err := aiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ASNInfo IDs.
func (aiq *ASNInfoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if aiq.ctx.Unique == nil && aiq.path != nil {
		aiq.Unique(true)
	}
	ctx = setContextOp(ctx, aiq.ctx, ent.OpQueryIDs)
	if err = aiq.Select(asninfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aiq *ASNInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := aiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aiq *ASNInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aiq.ctx, ent.OpQueryCount)
	if err := aiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aiq, querierCount[*ASNInfoQuery](), aiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aiq *ASNInfoQuery) CountX(ctx context.Context) int {
	count, err := aiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aiq *ASNInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aiq.ctx, ent.OpQueryExist)
	switch _, err := aiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("model_ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aiq *ASNInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := aiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ASNInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aiq *ASNInfoQuery) Clone() *ASNInfoQuery {
	if aiq == nil {
		return nil
	}
	return &ASNInfoQuery{
		config:     aiq.config,
		ctx:        aiq.ctx.Clone(),
		order:      append([]asninfo.OrderOption{}, aiq.order...),
		inters:     append([]Interceptor{}, aiq.inters...),
		predicates: append([]predicate.ASNInfo{}, aiq.predicates...),
		// clone intermediate query.
		sql:  aiq.sql.Clone(),
		path: aiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Asn int `json:"asn,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ASNInfo.Query().
//		GroupBy(asninfo.FieldAsn).
//		Aggregate(model_ent.Count()).
//		Scan(ctx, &v)
func (aiq *ASNInfoQuery) GroupBy(field string, fields ...string) *ASNInfoGroupBy {
	aiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ASNInfoGroupBy{build: aiq}
	grbuild.flds = &aiq.ctx.Fields
	grbuild.label = asninfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Asn int `json:"asn,omitempty"`
//	}
//
//	client.ASNInfo.Query().
//		Select(asninfo.FieldAsn).
//		Scan(ctx, &v)
func (aiq *ASNInfoQuery) Select(fields ...string) *ASNInfoSelect {
	aiq.ctx.Fields = append(aiq.ctx.Fields, fields...)
	sbuild := &ASNInfoSelect{ASNInfoQuery: aiq}
	sbuild.label = asninfo.Label
	sbuild.flds, sbuild.scan = &aiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ASNInfoSelect configured with the given aggregations.
func (aiq *ASNInfoQuery) Aggregate(fns ...AggregateFunc) *ASNInfoSelect {
	return aiq.Select().Aggregate(fns...)
}

func (aiq *ASNInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aiq.inters {
		if inter == nil {
			return fmt.Errorf("model_ent: uninitialized interceptor (forgotten import model_ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aiq); err != nil {
				return err
			}
		}
	}
	for _, f := range aiq.ctx.Fields {
		if !asninfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("model_ent: invalid field %q for query", f)}
		}
	}
	if aiq.path != nil {
		prev, err := aiq.path(ctx)
		if err != nil {
			return err
		}
		aiq.sql = prev
	}
	return nil
}

func (aiq *ASNInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ASNInfo, error) {
	var (
		nodes   = []*ASNInfo{}
		withFKs = aiq.withFKs
		_spec   = aiq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, asninfo.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ASNInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ASNInfo{config: aiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aiq *ASNInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aiq.querySpec()
	_spec.Node.Columns = aiq.ctx.Fields
	if len(aiq.ctx.Fields) > 0 {
		_spec.Unique = aiq.ctx.Unique != nil && *aiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aiq.driver, _spec)
}

func (aiq *ASNInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(asninfo.Table, asninfo.Columns, sqlgraph.NewFieldSpec(asninfo.FieldID, field.TypeInt))
	_spec.From = aiq.sql
	if unique := aiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aiq.path != nil {
		_spec.Unique = true
	}
	if fields := aiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asninfo.FieldID)
		for i := range fields {
			if fields[i] != asninfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aiq *ASNInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aiq.driver.Dialect())
	t1 := builder.Table(asninfo.Table)
	columns := aiq.ctx.Fields
	if len(columns) == 0 {
		columns = asninfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aiq.sql != nil {
		selector = aiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aiq.ctx.Unique != nil && *aiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aiq.predicates {
		p(selector)
	}
	for _, p := range aiq.order {
		p(selector)
	}
	if offset := aiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ASNInfoGroupBy is the group-by builder for ASNInfo entities.
type ASNInfoGroupBy struct {
	selector
	build *ASNInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aigb *ASNInfoGroupBy) Aggregate(fns ...AggregateFunc) *ASNInfoGroupBy {
	aigb.fns = append(aigb.fns, fns...)
	return aigb
}

// Scan applies the selector query and scans the result into the given value.
func (aigb *ASNInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aigb.build.ctx, ent.OpQueryGroupBy)
	if err := aigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ASNInfoQuery, *ASNInfoGroupBy](ctx, aigb.build, aigb, aigb.build.inters, v)
}

func (aigb *ASNInfoGroupBy) sqlScan(ctx context.Context, root *ASNInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aigb.fns))
	for _, fn := range aigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aigb.flds)+len(aigb.fns))
		for _, f := range *aigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ASNInfoSelect is the builder for selecting fields of ASNInfo entities.
type ASNInfoSelect struct {
	*ASNInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ais *ASNInfoSelect) Aggregate(fns ...AggregateFunc) *ASNInfoSelect {
	ais.fns = append(ais.fns, fns...)
	return ais
}

// Scan applies the selector query and scans the result into the given value.
func (ais *ASNInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ais.ctx, ent.OpQuerySelect)
	if err := ais.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ASNInfoQuery, *ASNInfoSelect](ctx, ais.ASNInfoQuery, ais, ais.inters, v)
}

func (ais *ASNInfoSelect) sqlScan(ctx context.Context, root *ASNInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ais.fns))
	for _, fn := range ais.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ais.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ais.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
