openapi: 3.0.0
info:
  title: Domain Name Hist API
  version: 1.0.0
paths:
  /data:
    get:
      summary: Get information about available data types
      tags:
        - Query Data
      operationId: getDataMeta
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataResponse'
        '400':
          description: Generic request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /data/{type}:
    get:
      summary: Get data details
      operationId: getDataDetails
      tags:
        - Query Data
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: domain
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataResponse'
        '400':
          description: Generic request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Malformed request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /scan:
    summary: Scan-related functions
    post:
      summary: Start a Scan
      tags:
        - Scanning
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataRequest'
      operationId: startScan
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataResponse'
        '422':
          description: Malformed request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    DataRequest:
      type: object
      properties:
        data:
          type: string
        meta:
          type: object
    DataResponse:
      type: object
      properties:
        data:
          type: object
        meta:
          type: object
    ErrorResponse:
      type: object
      properties:
        meta:
          type: object
        errors:
          type: array
          items:
            properties:
              type:
                $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        code:
          type: string
        title:
          type: string
        detail:
          type: string
